In [4]:
import sys
import pandas as pd
import plotly

print(sys.version)
print("")
print(f"pandas:      version {pd.__version__}")
print(f"plotly:      version {plotly.__version__}")

3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0]

pandas:      version 1.1.1
plotly:      version 4.10.0

In [27]:
ny = pd.read_csv("../data/weather/new_york_ny.csv")

print(ny.shape)
ny.head()

(17056, 25)

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2009-01-01 00:00:00,0,0,0.0,8.7,2,31,11:07 AM,10:50 PM,08:20 AM,...,38,22,62,0.0,1017,-6,10,316,27,10007
1,2009-01-01 06:00:00,0,0,0.0,8.7,2,31,11:07 AM,10:50 PM,08:20 AM,...,33,7,63,0.0,1023,-8,10,315,24,10007
2,2009-01-01 12:00:00,0,0,0.0,8.7,2,31,11:07 AM,10:50 PM,08:20 AM,...,26,4,42,0.0,1025,-3,10,304,23,10007
3,2009-01-01 18:00:00,0,0,0.0,8.7,2,31,11:07 AM,10:50 PM,08:20 AM,...,21,16,49,0.0,1025,-5,10,294,13,10007
4,2009-01-02 00:00:00,0,0,0.1,7.0,2,38,11:28 AM,11:54 PM,08:20 AM,...,14,46,49,0.0,1023,-6,10,260,8,10007

In [28]:
ny.columns

Index(['date_time', 'maxtempC', 'mintempC', 'totalSnow_cm', 'sunHour',
       'uvIndex', 'moon_illumination', 'moonrise', 'moonset', 'sunrise',
       'sunset', 'DewPointC', 'FeelsLikeC', 'HeatIndexC', 'WindChillC',
       'WindGustKmph', 'cloudcover', 'humidity', 'precipMM', 'pressure',
       'tempC', 'visibility', 'winddirDegree', 'windspeedKmph', 'location'],
      dtype='object')

In [29]:
ny.dtypes

date_time             object
maxtempC               int64
mintempC               int64
totalSnow_cm         float64
sunHour              float64
uvIndex                int64
moon_illumination      int64
moonrise              object
moonset               object
sunrise               object
sunset                object
DewPointC              int64
FeelsLikeC             int64
HeatIndexC             int64
WindChillC             int64
WindGustKmph           int64
cloudcover             int64
humidity               int64
precipMM             float64
pressure               int64
tempC                  int64
visibility             int64
winddirDegree          int64
windspeedKmph          int64
location               int64
dtype: object

In [30]:
ny.date_time

0        2009-01-01 00:00:00
1        2009-01-01 06:00:00
2        2009-01-01 12:00:00
3        2009-01-01 18:00:00
4        2009-01-02 00:00:00
                ...
17051    2020-09-02 18:00:00
17052    2020-09-03 00:00:00
17053    2020-09-03 06:00:00
17054    2020-09-03 12:00:00
17055    2020-09-03 18:00:00
Name: date_time, Length: 17056, dtype: object

In [11]:
# Checking date_time format

date = df.date_time[0]
print(type(date), date)

<class 'str'> 2009-01-01 00:00:00

In [31]:
from datetime import datetime

# Applying change to all dates
ny.date_time = ny.date_time.apply(lambda d: datetime.strptime(d, '%Y-%m-%d %H:%M:%S'))
ny.date_time.head()

0   2009-01-01 00:00:00
1   2009-01-01 06:00:00
2   2009-01-01 12:00:00
3   2009-01-01 18:00:00
4   2009-01-02 00:00:00
Name: date_time, dtype: datetime64[ns]

In [14]:
splits = []

for i in range(2009, 2021):
    for j in range(1, 13):
        splits.append(datetime(i, j, 1))
    
print(splits)

[datetime.datetime(2009, 1, 1, 0, 0), datetime.datetime(2009, 2, 1, 0, 0), datetime.datetime(2009, 3, 1, 0, 0), datetime.datetime(2009, 4, 1, 0, 0), datetime.datetime(2009, 5, 1, 0, 0), datetime.datetime(2009, 6, 1, 0, 0), datetime.datetime(2009, 7, 1, 0, 0), datetime.datetime(2009, 8, 1, 0, 0), datetime.datetime(2009, 9, 1, 0, 0), datetime.datetime(2009, 10, 1, 0, 0), datetime.datetime(2009, 11, 1, 0, 0), datetime.datetime(2009, 12, 1, 0, 0), datetime.datetime(2010, 1, 1, 0, 0), datetime.datetime(2010, 2, 1, 0, 0), datetime.datetime(2010, 3, 1, 0, 0), datetime.datetime(2010, 4, 1, 0, 0), datetime.datetime(2010, 5, 1, 0, 0), datetime.datetime(2010, 6, 1, 0, 0), datetime.datetime(2010, 7, 1, 0, 0), datetime.datetime(2010, 8, 1, 0, 0), datetime.datetime(2010, 9, 1, 0, 0), datetime.datetime(2010, 10, 1, 0, 0), datetime.datetime(2010, 11, 1, 0, 0), datetime.datetime(2010, 12, 1, 0, 0), datetime.datetime(2011, 1, 1, 0, 0), datetime.datetime(2011, 2, 1, 0, 0), datetime.datetime(2011, 3, 1, 0, 0), datetime.datetime(2011, 4, 1, 0, 0), datetime.datetime(2011, 5, 1, 0, 0), datetime.datetime(2011, 6, 1, 0, 0), datetime.datetime(2011, 7, 1, 0, 0), datetime.datetime(2011, 8, 1, 0, 0), datetime.datetime(2011, 9, 1, 0, 0), datetime.datetime(2011, 10, 1, 0, 0), datetime.datetime(2011, 11, 1, 0, 0), datetime.datetime(2011, 12, 1, 0, 0), datetime.datetime(2012, 1, 1, 0, 0), datetime.datetime(2012, 2, 1, 0, 0), datetime.datetime(2012, 3, 1, 0, 0), datetime.datetime(2012, 4, 1, 0, 0), datetime.datetime(2012, 5, 1, 0, 0), datetime.datetime(2012, 6, 1, 0, 0), datetime.datetime(2012, 7, 1, 0, 0), datetime.datetime(2012, 8, 1, 0, 0), datetime.datetime(2012, 9, 1, 0, 0), datetime.datetime(2012, 10, 1, 0, 0), datetime.datetime(2012, 11, 1, 0, 0), datetime.datetime(2012, 12, 1, 0, 0), datetime.datetime(2013, 1, 1, 0, 0), datetime.datetime(2013, 2, 1, 0, 0), datetime.datetime(2013, 3, 1, 0, 0), datetime.datetime(2013, 4, 1, 0, 0), datetime.datetime(2013, 5, 1, 0, 0), datetime.datetime(2013, 6, 1, 0, 0), datetime.datetime(2013, 7, 1, 0, 0), datetime.datetime(2013, 8, 1, 0, 0), datetime.datetime(2013, 9, 1, 0, 0), datetime.datetime(2013, 10, 1, 0, 0), datetime.datetime(2013, 11, 1, 0, 0), datetime.datetime(2013, 12, 1, 0, 0), datetime.datetime(2014, 1, 1, 0, 0), datetime.datetime(2014, 2, 1, 0, 0), datetime.datetime(2014, 3, 1, 0, 0), datetime.datetime(2014, 4, 1, 0, 0), datetime.datetime(2014, 5, 1, 0, 0), datetime.datetime(2014, 6, 1, 0, 0), datetime.datetime(2014, 7, 1, 0, 0), datetime.datetime(2014, 8, 1, 0, 0), datetime.datetime(2014, 9, 1, 0, 0), datetime.datetime(2014, 10, 1, 0, 0), datetime.datetime(2014, 11, 1, 0, 0), datetime.datetime(2014, 12, 1, 0, 0), datetime.datetime(2015, 1, 1, 0, 0), datetime.datetime(2015, 2, 1, 0, 0), datetime.datetime(2015, 3, 1, 0, 0), datetime.datetime(2015, 4, 1, 0, 0), datetime.datetime(2015, 5, 1, 0, 0), datetime.datetime(2015, 6, 1, 0, 0), datetime.datetime(2015, 7, 1, 0, 0), datetime.datetime(2015, 8, 1, 0, 0), datetime.datetime(2015, 9, 1, 0, 0), datetime.datetime(2015, 10, 1, 0, 0), datetime.datetime(2015, 11, 1, 0, 0), datetime.datetime(2015, 12, 1, 0, 0), datetime.datetime(2016, 1, 1, 0, 0), datetime.datetime(2016, 2, 1, 0, 0), datetime.datetime(2016, 3, 1, 0, 0), datetime.datetime(2016, 4, 1, 0, 0), datetime.datetime(2016, 5, 1, 0, 0), datetime.datetime(2016, 6, 1, 0, 0), datetime.datetime(2016, 7, 1, 0, 0), datetime.datetime(2016, 8, 1, 0, 0), datetime.datetime(2016, 9, 1, 0, 0), datetime.datetime(2016, 10, 1, 0, 0), datetime.datetime(2016, 11, 1, 0, 0), datetime.datetime(2016, 12, 1, 0, 0), datetime.datetime(2017, 1, 1, 0, 0), datetime.datetime(2017, 2, 1, 0, 0), datetime.datetime(2017, 3, 1, 0, 0), datetime.datetime(2017, 4, 1, 0, 0), datetime.datetime(2017, 5, 1, 0, 0), datetime.datetime(2017, 6, 1, 0, 0), datetime.datetime(2017, 7, 1, 0, 0), datetime.datetime(2017, 8, 1, 0, 0), datetime.datetime(2017, 9, 1, 0, 0), datetime.datetime(2017, 10, 1, 0, 0), datetime.datetime(2017, 11, 1, 0, 0), datetime.datetime(2017, 12, 1, 0, 0), datetime.datetime(2018, 1, 1, 0, 0), datetime.datetime(2018, 2, 1, 0, 0), datetime.datetime(2018, 3, 1, 0, 0), datetime.datetime(2018, 4, 1, 0, 0), datetime.datetime(2018, 5, 1, 0, 0), datetime.datetime(2018, 6, 1, 0, 0), datetime.datetime(2018, 7, 1, 0, 0), datetime.datetime(2018, 8, 1, 0, 0), datetime.datetime(2018, 9, 1, 0, 0), datetime.datetime(2018, 10, 1, 0, 0), datetime.datetime(2018, 11, 1, 0, 0), datetime.datetime(2018, 12, 1, 0, 0), datetime.datetime(2019, 1, 1, 0, 0), datetime.datetime(2019, 2, 1, 0, 0), datetime.datetime(2019, 3, 1, 0, 0), datetime.datetime(2019, 4, 1, 0, 0), datetime.datetime(2019, 5, 1, 0, 0), datetime.datetime(2019, 6, 1, 0, 0), datetime.datetime(2019, 7, 1, 0, 0), datetime.datetime(2019, 8, 1, 0, 0), datetime.datetime(2019, 9, 1, 0, 0), datetime.datetime(2019, 10, 1, 0, 0), datetime.datetime(2019, 11, 1, 0, 0), datetime.datetime(2019, 12, 1, 0, 0), datetime.datetime(2020, 1, 1, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 8, 1, 0, 0), datetime.datetime(2020, 9, 1, 0, 0), datetime.datetime(2020, 10, 1, 0, 0), datetime.datetime(2020, 11, 1, 0, 0), datetime.datetime(2020, 12, 1, 0, 0)]

In [15]:
csv_files = [file for file in os.listdir(os.path.join("..", "data", "weather")) if file[-3:]  == "csv"]
print(len(csv_files))
print(csv_files)

76
['albuquerque_nm.csv', 'anchorage_ak.csv', 'annapolis_md.csv', 'atlanta_ga.csv', 'augusta_ga.csv', 'aurora_il.csv', 'austin_tx.csv', 'baltimore_md.csv', 'bandon_or.csv', 'baton_rouge_la.csv', 'bethlehem_pa.csv', 'biloxi_ms.csv', 'boston_ma.csv', 'buffalo_ny.csv', 'charleston_wv.csv', 'chicago_il.csv', 'colorado_springs_co.csv', 'columbia_sc.csv', 'dallas_tx.csv', 'denver_co.csv', 'dover_de.csv', 'durham_nc.csv', 'fort_smith_ar.csv', 'fort_wayne_in.csv', 'hempstead_ny.csv', 'houston_tx.csv', 'huntington_wv.csv', 'indianapolis_in.csv', 'jacksonville_fl.csv', 'jackson_ms.csv', 'jersey_city_nj.csv', 'kenmore_wa.csv', 'knoxville_tn.csv', 'las_cruces_nm.csv', 'las_vegas_nv.csv', 'lexington_ky.csv', 'little_rock_ar.csv', 'los_angeles_ca.csv', 'louisville_ky.csv', 'memphis_tn.csv', 'miami_fl.csv', 'mobile_al.csv', 'montgomery_al.csv', 'myrtle_beach_sc.csv', 'nashville_tn.csv', 'newark_nj.csv', 'new_orleans_la.csv', 'new_york_ny.csv', 'norfolk_va.csv', 'philidelphia_pa.csv', 'phoenix_az.csv', 'pittsburgh_pa.csv', 'portland_or.csv', 'provo_ut.csv', 'raleigh_nc.csv', 'reno_nv.csv', 'richmond_va.csv', 'sacramento_ca.csv', 'saint_george.csv', 'salem_or.csv', 'salt_lake_city_ut.csv', 'san_antonio_tx.csv', 'san_diego_ca.csv', 'san_francisco_ca.csv', 'san_jose_ca.csv', 'savannah_ga.csv', 'seattle_wa.csv', 'spokane_wa.csv', 'springfield_ma.csv', 'tallahassee_fl.csv', 'topeka_ks.csv', 'tuscon_az.csv', 'virginia_beach_va.csv', 'washington_dc.csv', 'wichita_ks.csv', 'wilmington_de.csv']

In [22]:
set_ = set()

for file in csv_files:
    filenames.append(file)
    DataFrame = pd.read_csv(f"../data/weather/{file}")
    set_.add(len(DataFrame.index))
    
set_

{16440, 17044, 17056}

In [25]:
dict_ = dict()

for file in csv_files:
    filenames.append(file)
    DataFrame = pd.read_csv(f"../data/weather/{file}")
    dict_[file] = len(DataFrame.index)
    
print(dict_)

{'albuquerque_nm.csv': 16440, 'anchorage_ak.csv': 16440, 'annapolis_md.csv': 17056, 'atlanta_ga.csv': 17056, 'augusta_ga.csv': 17056, 'aurora_il.csv': 17056, 'austin_tx.csv': 17044, 'baltimore_md.csv': 17056, 'bandon_or.csv': 16440, 'baton_rouge_la.csv': 17056, 'bethlehem_pa.csv': 16440, 'biloxi_ms.csv': 17056, 'boston_ma.csv': 16440, 'buffalo_ny.csv': 17056, 'charleston_wv.csv': 17056, 'chicago_il.csv': 17056, 'colorado_springs_co.csv': 16440, 'columbia_sc.csv': 17056, 'dallas_tx.csv': 17056, 'denver_co.csv': 16440, 'dover_de.csv': 17056, 'durham_nc.csv': 17056, 'fort_smith_ar.csv': 17056, 'fort_wayne_in.csv': 17056, 'hempstead_ny.csv': 17056, 'houston_tx.csv': 17056, 'huntington_wv.csv': 17056, 'indianapolis_in.csv': 17056, 'jacksonville_fl.csv': 16440, 'jackson_ms.csv': 17056, 'jersey_city_nj.csv': 16440, 'kenmore_wa.csv': 16440, 'knoxville_tn.csv': 17056, 'las_cruces_nm.csv': 17044, 'las_vegas_nv.csv': 16440, 'lexington_ky.csv': 17056, 'little_rock_ar.csv': 17056, 'los_angeles_ca.csv': 17056, 'louisville_ky.csv': 17056, 'memphis_tn.csv': 17056, 'miami_fl.csv': 17056, 'mobile_al.csv': 17056, 'montgomery_al.csv': 17056, 'myrtle_beach_sc.csv': 17056, 'nashville_tn.csv': 17056, 'newark_nj.csv': 16440, 'new_orleans_la.csv': 17056, 'new_york_ny.csv': 17056, 'norfolk_va.csv': 17056, 'philidelphia_pa.csv': 17056, 'phoenix_az.csv': 16440, 'pittsburgh_pa.csv': 16440, 'portland_or.csv': 17056, 'provo_ut.csv': 17044, 'raleigh_nc.csv': 17056, 'reno_nv.csv': 16440, 'richmond_va.csv': 17056, 'sacramento_ca.csv': 16440, 'saint_george.csv': 17044, 'salem_or.csv': 17056, 'salt_lake_city_ut.csv': 17044, 'san_antonio_tx.csv': 16440, 'san_diego_ca.csv': 17044, 'san_francisco_ca.csv': 17056, 'san_jose_ca.csv': 17056, 'savannah_ga.csv': 17056, 'seattle_wa.csv': 17056, 'spokane_wa.csv': 17056, 'springfield_ma.csv': 16440, 'tallahassee_fl.csv': 17056, 'topeka_ks.csv': 17056, 'tuscon_az.csv': 16440, 'virginia_beach_va.csv': 17056, 'washington_dc.csv': 17056, 'wichita_ks.csv': 17056, 'wilmington_de.csv': 17056}

In [26]:
# Can store in individual .py file to keep track of .csv length
# dict_ can then be imported 

for file in dict_:
    if dict_[file] == 16440:
        dict_[file] = "short"
        
    elif dict_[file] == 17044 or dict_[file] == 17056:
        dict_[file] = "long"
        
print(dict_)

{'albuquerque_nm.csv': 'short', 'anchorage_ak.csv': 'short', 'annapolis_md.csv': 'long', 'atlanta_ga.csv': 'long', 'augusta_ga.csv': 'long', 'aurora_il.csv': 'long', 'austin_tx.csv': 'long', 'baltimore_md.csv': 'long', 'bandon_or.csv': 'short', 'baton_rouge_la.csv': 'long', 'bethlehem_pa.csv': 'short', 'biloxi_ms.csv': 'long', 'boston_ma.csv': 'short', 'buffalo_ny.csv': 'long', 'charleston_wv.csv': 'long', 'chicago_il.csv': 'long', 'colorado_springs_co.csv': 'short', 'columbia_sc.csv': 'long', 'dallas_tx.csv': 'long', 'denver_co.csv': 'short', 'dover_de.csv': 'long', 'durham_nc.csv': 'long', 'fort_smith_ar.csv': 'long', 'fort_wayne_in.csv': 'long', 'hempstead_ny.csv': 'long', 'houston_tx.csv': 'long', 'huntington_wv.csv': 'long', 'indianapolis_in.csv': 'long', 'jacksonville_fl.csv': 'short', 'jackson_ms.csv': 'long', 'jersey_city_nj.csv': 'short', 'kenmore_wa.csv': 'short', 'knoxville_tn.csv': 'long', 'las_cruces_nm.csv': 'long', 'las_vegas_nv.csv': 'short', 'lexington_ky.csv': 'long', 'little_rock_ar.csv': 'long', 'los_angeles_ca.csv': 'long', 'louisville_ky.csv': 'long', 'memphis_tn.csv': 'long', 'miami_fl.csv': 'long', 'mobile_al.csv': 'long', 'montgomery_al.csv': 'long', 'myrtle_beach_sc.csv': 'long', 'nashville_tn.csv': 'long', 'newark_nj.csv': 'short', 'new_orleans_la.csv': 'long', 'new_york_ny.csv': 'long', 'norfolk_va.csv': 'long', 'philidelphia_pa.csv': 'long', 'phoenix_az.csv': 'short', 'pittsburgh_pa.csv': 'short', 'portland_or.csv': 'long', 'provo_ut.csv': 'long', 'raleigh_nc.csv': 'long', 'reno_nv.csv': 'short', 'richmond_va.csv': 'long', 'sacramento_ca.csv': 'short', 'saint_george.csv': 'long', 'salem_or.csv': 'long', 'salt_lake_city_ut.csv': 'long', 'san_antonio_tx.csv': 'short', 'san_diego_ca.csv': 'long', 'san_francisco_ca.csv': 'long', 'san_jose_ca.csv': 'long', 'savannah_ga.csv': 'long', 'seattle_wa.csv': 'long', 'spokane_wa.csv': 'long', 'springfield_ma.csv': 'short', 'tallahassee_fl.csv': 'long', 'topeka_ks.csv': 'long', 'tuscon_az.csv': 'short', 'virginia_beach_va.csv': 'long', 'washington_dc.csv': 'long', 'wichita_ks.csv': 'long', 'wilmington_de.csv': 'long'}

In [33]:
an = pd.read_csv(f"../data/weather/anchorage_ak.csv")

print(an.shape)
an.head()

(16440, 25)

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2009-03-01 00:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,18,10,96,0.0,1018,-11,2,337,9,99501
1,2009-03-01 06:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,23,0,94,0.0,1017,-12,2,349,12,99501
2,2009-03-01 12:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,23,41,95,0.0,1016,-11,10,320,17,99501
3,2009-03-01 18:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,26,5,95,0.0,1016,-12,9,331,16,99501
4,2009-03-02 00:00:00,0,0,0.0,10.7,1,37,09:06 AM,03:24 AM,08:56 AM,...,21,0,96,0.0,1017,-15,2,13,11,99501

In [47]:
an.tail()

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
16435,2020-05-30 18:00:00,10,1,0.0,14.1,3,54,01:52 PM,03:56 AM,04:38 AM,...,8,88,80,0.5,1007,6,5,187,4,99501
16436,2020-05-31 00:00:00,11,3,0.0,14.1,2,58,03:29 PM,04:03 AM,04:36 AM,...,5,87,84,0.2,1007,7,7,165,3,99501
16437,2020-05-31 06:00:00,11,3,0.0,14.1,2,58,03:29 PM,04:03 AM,04:36 AM,...,3,98,89,0.2,1007,9,5,314,2,99501
16438,2020-05-31 12:00:00,11,3,0.0,14.1,2,58,03:29 PM,04:03 AM,04:36 AM,...,6,84,78,0.1,1006,10,10,296,4,99501
16439,2020-05-31 18:00:00,11,3,0.0,14.1,2,58,03:29 PM,04:03 AM,04:36 AM,...,17,62,68,0.1,1005,8,10,139,10,99501

In [36]:
an.date_time = an.date_time.apply(lambda d: datetime.strptime(d, '%Y-%m-%d %H:%M:%S'))
an.date_time.head()

0   2009-03-01 00:00:00
1   2009-03-01 06:00:00
2   2009-03-01 12:00:00
3   2009-03-01 18:00:00
4   2009-03-02 00:00:00
Name: date_time, dtype: datetime64[ns]

In [40]:
# Testing short split:)

# i=1 for long split, i=3 for short split

march_2009 = an[an.date_time < splits[3]]

print(march_2009.shape)
march_2009

(124, 25)

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2009-03-01 00:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,18,10,96,0.0,1018,-11,2,337,9,99501
1,2009-03-01 06:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,23,0,94,0.0,1017,-12,2,349,12,99501
2,2009-03-01 12:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,23,41,95,0.0,1016,-11,10,320,17,99501
3,2009-03-01 18:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,26,5,95,0.0,1016,-12,9,331,16,99501
4,2009-03-02 00:00:00,0,0,0.0,10.7,1,37,09:06 AM,03:24 AM,08:56 AM,...,21,0,96,0.0,1017,-15,2,13,11,99501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2009-03-30 18:00:00,0,0,1.9,7.8,1,26,07:30 AM,02:48 AM,07:28 AM,...,11,77,96,0.0,1003,-6,10,239,8,99501
120,2009-03-31 00:00:00,0,0,0.1,11.6,1,30,07:58 AM,04:26 AM,07:25 AM,...,7,45,96,0.0,1008,-14,2,197,3,99501
121,2009-03-31 06:00:00,0,0,0.1,11.6,1,30,07:58 AM,04:26 AM,07:25 AM,...,13,55,96,0.1,1012,-10,7,122,7,99501
122,2009-03-31 12:00:00,0,0,0.1,11.6,1,30,07:58 AM,04:26 AM,07:25 AM,...,4,29,94,0.0,1011,-5,10,23,4,99501
123,2009-03-31 18:00:00,0,0,0.1,11.6,1,30,07:58 AM,04:26 AM,07:25 AM,...,10,28,96,0.0,1010,-4,10,39,6,99501

In [48]:
subsets = []

subsets.append(march_2009)

# splits[3:-3] for short, splits[1:-2] for long

for j in range(len(splits[3:-3]) - 1):
    subset = an[an.date_time > splits[j]]
    subset = subset[subset.date_time < splits[j + 1]]
    subset = subset.reset_index(drop=True)
    subsets.append(subset)
    
subsets[0]

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2009-03-01 00:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,18,10,96,0.0,1018,-11,2,337,9,99501
1,2009-03-01 06:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,23,0,94,0.0,1017,-12,2,349,12,99501
2,2009-03-01 12:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,23,41,95,0.0,1016,-11,10,320,17,99501
3,2009-03-01 18:00:00,0,0,0.0,10.7,1,30,09:01 AM,01:39 AM,08:59 AM,...,26,5,95,0.0,1016,-12,9,331,16,99501
4,2009-03-02 00:00:00,0,0,0.0,10.7,1,37,09:06 AM,03:24 AM,08:56 AM,...,21,0,96,0.0,1017,-15,2,13,11,99501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,2009-03-30 18:00:00,0,0,1.9,7.8,1,26,07:30 AM,02:48 AM,07:28 AM,...,11,77,96,0.0,1003,-6,10,239,8,99501
120,2009-03-31 00:00:00,0,0,0.1,11.6,1,30,07:58 AM,04:26 AM,07:25 AM,...,7,45,96,0.0,1008,-14,2,197,3,99501
121,2009-03-31 06:00:00,0,0,0.1,11.6,1,30,07:58 AM,04:26 AM,07:25 AM,...,13,55,96,0.1,1012,-10,7,122,7,99501
122,2009-03-31 12:00:00,0,0,0.1,11.6,1,30,07:58 AM,04:26 AM,07:25 AM,...,4,29,94,0.0,1011,-5,10,23,4,99501
123,2009-03-31 18:00:00,0,0,0.1,11.6,1,30,07:58 AM,04:26 AM,07:25 AM,...,10,28,96,0.0,1010,-4,10,39,6,99501

In [46]:
subsets[-1]

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2020-05-01 06:00:00,7,0,0.0,14.9,1,58,12:58 PM,05:25 AM,05:49 AM,...,5,39,81,0.1,1014,3,10,85,3,99501
1,2020-05-01 12:00:00,7,0,0.0,14.9,1,58,12:58 PM,05:25 AM,05:49 AM,...,7,72,69,0.1,1016,5,10,359,4,99501
2,2020-05-01 18:00:00,7,0,0.0,14.9,1,58,12:58 PM,05:25 AM,05:49 AM,...,5,45,56,0.1,1015,5,10,299,3,99501
3,2020-05-02 00:00:00,7,0,0.0,16.6,1,65,02:37 PM,05:37 AM,05:46 AM,...,4,35,80,0.0,1015,3,10,267,3,99501
4,2020-05-02 06:00:00,7,0,0.0,16.6,1,65,02:37 PM,05:37 AM,05:46 AM,...,11,8,86,0.0,1014,1,10,354,7,99501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,2020-05-30 18:00:00,10,1,0.0,14.1,3,54,01:52 PM,03:56 AM,04:38 AM,...,8,88,80,0.5,1007,6,5,187,4,99501
119,2020-05-31 00:00:00,11,3,0.0,14.1,2,58,03:29 PM,04:03 AM,04:36 AM,...,5,87,84,0.2,1007,7,7,165,3,99501
120,2020-05-31 06:00:00,11,3,0.0,14.1,2,58,03:29 PM,04:03 AM,04:36 AM,...,3,98,89,0.2,1007,9,5,314,2,99501
121,2020-05-31 12:00:00,11,3,0.0,14.1,2,58,03:29 PM,04:03 AM,04:36 AM,...,6,84,78,0.1,1006,10,10,296,4,99501
122,2020-05-31 18:00:00,11,3,0.0,14.1,2,58,03:29 PM,04:03 AM,04:36 AM,...,17,62,68,0.1,1005,8,10,139,10,99501

In [53]:
subsets = []

subsets.append(jan_2009)

# Loop through splits array
for j in range(len(splits[1:-2]) - 1):
    subset = ny[ny.date_time > splits[j]]
    subset = subset[subset.date_time < splits[j + 1]]
    subset = subset.reset_index(drop=True)
    subsets.append(subset)
    
subsets[-1]

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2020-08-01 06:00:00,29,25,0.0,14.5,7,82,07:08 PM,03:31 AM,05:53 AM,...,12,5,71,0.0,1012,25,10,228,9,10007
1,2020-08-01 12:00:00,29,25,0.0,14.5,7,82,07:08 PM,03:31 AM,05:53 AM,...,12,6,56,0.0,1014,28,10,98,10,10007
2,2020-08-01 18:00:00,29,25,0.0,14.5,7,82,07:08 PM,03:31 AM,05:53 AM,...,28,19,64,0.0,1013,27,10,155,20,10007
3,2020-08-02 00:00:00,31,25,0.0,10.2,7,90,07:56 PM,04:30 AM,05:54 AM,...,22,43,74,0.0,1015,25,10,179,15,10007
4,2020-08-02 06:00:00,31,25,0.0,10.2,7,90,07:56 PM,04:30 AM,05:54 AM,...,23,73,85,0.0,1014,25,10,163,17,10007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,2020-08-30 18:00:00,26,20,0.0,11.6,6,79,06:35 PM,03:24 AM,06:21 AM,...,13,19,52,0.0,1009,26,10,315,11,10007
119,2020-08-31 00:00:00,23,21,0.0,10.3,6,82,07:10 PM,04:27 AM,06:22 AM,...,15,3,54,0.0,1014,24,10,251,12,10007
120,2020-08-31 06:00:00,23,21,0.0,10.3,6,82,07:10 PM,04:27 AM,06:22 AM,...,17,15,58,0.0,1016,21,10,62,12,10007
121,2020-08-31 12:00:00,23,21,0.0,10.3,6,82,07:10 PM,04:27 AM,06:22 AM,...,20,72,59,0.0,1019,23,10,116,17,10007
122,2020-08-31 18:00:00,23,21,0.0,10.3,6,82,07:10 PM,04:27 AM,06:22 AM,...,23,28,68,0.0,1018,23,10,127,18,10007